const products = [
  {
    _id: '1',
    name: 'Help Elephants in Burma',
    image: '/images/elephant.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Elephant Sanctuary',
    category: 'Wildlife',
    donate: 10,
    donationNeedRemain: 0,
    donationGoal: 4500,
    percentageDonation: 100,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Help stray dogs in Argentina ',
    image: '/images/dog.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Doggie do Good',
    category: 'Stray animals',
    donate: 5,
    donationNeedRemain: 4600,
    donationGoal: 41000,
    percentageDonation: 40.5,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Help wildlife conservation in Zambia',
    image: '/images/lion.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Wild at Heart',
    category: 'Wildlife',
    donate: 10,
    donationNeedRemain: 7000,
    donationGoal: 45000,
    percentageDonation: 77.5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Help stray cats in Greece',
    image: '/images/kitten.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Sony',
    category: 'Stray animals',
    donate: 15,
    donationNeedRemain: 3400,
    donationGoal: 11000,
    percentageDonation: 86.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Help wild horses in Spain',
    image: '/images/horse.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Horse Paradise',
    category: 'Wildlife',
    donate: 5,
    donationNeedRemain: 320,
    donationGoal: 4500,
    percentageDonation: 62,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Help sea lives at risks',
    image: '/images/whale.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Sea Lovers',
    category: 'Wildlife',
    donate: 15,
    donationNeedRemain: 6500,
    donationGoal: 9000,
    percentageDonation: 48,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Help end farm animals being tortured',
    image: '/images/cow.png',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    charity: 'Happy Farm',
    category: 'Farm animals',
    donate: 12,
    donationNeedRemain: 2300,
    donationGoal: 67600,
    percentageDonation: 99.5,
    numReviews: 12,
  },
]

export default products
